name: Primer Workflow

on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: pip install pytest
      - name: Ejecutar codigo
        run: pytest test.py
      - name: Crear imagen
        run: docker build -t Adrimr7/pruebaCICD .
      - name: Probar contenedor
        run: docker run Adrimr7/pruebaCICD 
