name: Primer Workflow

on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar msg
        run: echo "Hola Github Actions"
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: python3 main.py
